# ACCESS_KEY_ID = 'AKIAIZ2DWRMGDAY6B5PA'
# ACCESS_SECRET_KEY = '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'
# REGION_NAME = 'us-east-1'

ACCESS_KEY_ID = 'AKIAJZHAPZRIRTBEQU4A'
ACCESS_SECRET_KEY = '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'
REGION_NAME = 'us-east-1'